development:
  adapter: postgresql
  encoding: unicode
  database: this-app_development
  pool: 5
  username: austinthesing
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: this-app_test
  pool: 5
  username: austinthesing
  password:
